# Site settings
title: "Jose Antunes"
tagline: "Miscellaneous thoughts"
description: "Everyday learning and sharing"
url: "https://joseantunes.tech"
baseurl:
  ""
  # the optional subpath of your site, e.g. "/blog"
  # NB: This applies to all pages in your Jekyll site.
  # If you want to move just the blog index pages but keep
  # other pages at root, see the paginate_path and
  # sidebar_blog_link below.

# Author information
author:
  name: "Jose Antunes"
  linkedin: "https://linkedin.com/in/antunesjose"

# Build settings
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 5

# Comments
disqus:
  shortname: joseantunes-tech

# Analytics
google_analytics: "UA-28769373-2"
